version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TZ: Asia/Tokyo
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - app-network

  wp:
    depends_on:
      - db
    image: wordpress:php7.3-fpm-alpine
    container_name: wp
    ports:
      - '8080:80'
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp:/var/www/html
      # - ./conf/php:/usr/local/etc/php
      - ${WP_WORKING_THEME_DIR}:/var/www/html${WP_THEME_DIR}
    networks:
      - app-network

  web:
    depends_on:
      - wp
    image: nginx:1.15.12-alpine
    container_name: web
    restart: always
    ports:
      - '80:80'
    volumes:
      - wp:/var/www/html
      - ./conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network

volumes:
  db_data: {}
  wp: {}

networks:
  app-network:
    driver: bridge
